name: citcs_training_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0  # Latest version
  firebase_auth: ^4.17.0   # Latest version
  firebase_auth_web: ^5.8.13  # Add this if you're using web

  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Declare your assets here
  assets:
    - assets/images/logo.png
    - assets/images/bg_image.png
